import { NavBar } from '@/components/ui/NavBar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import About from '@/components/About/About'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='p-10 mr-[75px] ml-[75px]'>
        <NavBar></NavBar>
        {children}
        <About></About>
        </div>
      </body>
    </html>
  )
}
